on:
  repository_dispatch: 
    types: [incident_report]
jobs:
  handle-incident:
    runs-on: ubuntu-latest

    steps:
      - name: print incident details
        run: echo "incisent reporded " 
    
