on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - ".github/workflows/Push.yml"
      - "src/**"
      - "tests/**"
  pull_request:
    branches:
      - main
      - "release/**"
    paths:
      - ".github/workflows/Push.yml"
      - "src/**"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: instull npm
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
        working-directory: .

      - name: Run test 
        run: npm test
        working-directory: .

